<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'No results found' => 'No se han obtenido resultados',
  'About' => 'Quienes somos',
  'Account' => 'Cuenta',
  'Account information' => 'Cuenta de usuario para esta web',
  'Advanced Search' => 'Búsqueda avanzada',
  'Are you sure you want to delete this item?' => '¿Está seguro que desea eliminar este registro?',
  'Body' => 'Mensaje',
  'Bookmarks' => 'Favoritos',
  'Connect' => 'Conectar',
  'Contact' => 'Contacto',
  'Contact Us' => 'Contactar',
  'Create' => 'Crear',
  'Create Document' => 'Nuevo documento',
  'Create Document Bookmark' => 'Nuevo documento favorito',
  'Create Web' => 'Nueva web favorita',
  'Create Web Bookmark' => 'Nueva web favorita',
  'Database exception: does this site?' => 'Excepción: ¿existe esta página web?',
  'Date created' => 'Fecha creación',
  'Delete Bookmark' => 'Eliminar favorito',
  'Delete Document' => 'Eliminar documento',
  'Delete Web' => 'Eliminar web favorita',
  'Description' => 'Descripción',
  'Document type' => 'Tipo de documento',
  'Documents' => 'Documentos',
  'E-mail' => 'E-mail',
  'Fields with' => 'Los campos con',
  'File' => 'Fichero',
  'File extension' => 'Extensión',
  'Fill in this formulary if you have an account in this new web page with your account information' => 'Complete este formulario si tiene una cuenta en esta página web con su información de acceso',
  'If you have business inquiries or other questions, please fill out the following form to contact us' => 'Si tiene sugerencias o preguntas, por favor complete el siguiente formulario para contactar con nostros',
  'Import' => 'Importar',
  'Information' => 'Información',
  'Letters are not case-sensitive' => 'Las letras no son sensibles a mayúsculas y minúsculas',
  'List Bookmarks' => 'Lista de favoritos',
  'List Resource' => 'Lista de favoritos',
  'Load' => 'Cargar',
  'Logo' => 'Logotipo',
  'Logout' => 'Cerrar sesión',
  'Manage' => 'Gestión',
  'Manage Bookmark' => 'Gestión de favoritos',
  'Manage Document' => 'Gestión de documentos',
  'Manage Documents' => 'Gestión de documentos',
  'Manage Resources' => 'Gestión de favoritos',
  'Manage Web' => 'Gestión de favoritos web',
  'Manage Webs' => 'Gestión de webs',
  'Mime type' => 'Mime type',
  'Name' => 'Nombre',
  'Operations' => 'Operaciones',
  'Password' => 'Contraseña',
  'Please enter the letters as they are shown in the image above' => 'Por favor, inserta las letras que puede ver en la imagen de arriba',
  'Please fill out the following form with your login credentials' => 'Por favor, complete el siguiente formulario con tu usuario y contraseña para entrar al sistema',
  'Privacy' => 'Privacidad',
  'Private' => 'Privado',
  'Public' => 'Público',
  'Remember me next time' => 'Recuérdame la próxima vez',
  'Resources' => 'Favoritos',
  'Save' => 'Guardar',
  'Subject' => 'Asunto',
  'Submit1' => 'Enviar',
  'Tags' => 'Etiquetas',
  'Thank you' => 'Gracias',
  'The web has been inserted' => 'La web ha sido insertada',
  'This page has been made by' => 'Esta página ha sido creada por',
  'This web application is a bookmark with more options' => 'Esta apliación web es un gestor de favoritos con más opciones',
  'Update' => 'Modificar',
  'Update Bookmark' => 'Modificar favorito',
  'Update Document' => 'Modificar documento',
  'Update Web' => 'Modificar web favorita',
  'Username' => 'Usuario',
  'Verification Code' => 'Código de verificación',
  'View Bookmark' => 'Detalles del favorito',
  'View Document' => 'Detalle del documento',
  'View Web' => 'Detalle de la web favorita',
  'Webs' => 'Webs favoritas',
  'Welcome to' => 'Bienvenido a',
  'You can not access to that resource' => 'No puedes acceder al recurso',
  'You may optionally enter a comparison operator' => 'Usted puede, opcionalmente, introducir un operador de comparación',
  'are required' => 'son obligatorios',
  'at the beginning of each of your search values to specify how the comparison should be done' => 'al principio de cada una de sus búsquedas para indicar cómo debería hacerse la comparación',
  'or' => 'o',
);
