<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'About' => '',
  'Account' => '',
  'Account information' => '',
  'Advanced Search' => '',
  'Are you sure you want to delete this item?' => '',
  'Body' => '',
  'Bookmarks' => '',
  'Contact' => '',
  'Contact Us' => '',
  'Create' => '',
  'Create Document' => '',
  'Create Document Bookmark' => '',
  'Create Web' => '',
  'Create Web Bookmark' => '',
  'Date created' => '',
  'Delete Bookmark' => '',
  'Delete Document' => '',
  'Delete Web' => '',
  'Description' => '',
  'Document type' => '',
  'Documents' => '',
  'E-mail' => '',
  'Fields with' => '',
  'Fill in this formulary if you have an account in this new web page with your account information' => '',
  'If you have business inquiries or other questions, please fill out the following form to contact us' => '',
  'Letters are not case-sensitive' => '',
  'List Bookmarks' => '',
  'List Document' => '',
  'List Resource' => '',
  'List Web' => '',
  'Logo' => '',
  'Logout' => '',
  'Manage' => '',
  'Manage Bookmark' => '',
  'Manage Document' => '',
  'Manage Documents' => '',
  'Manage Resources' => '',
  'Manage Web' => '',
  'Manage Webs' => '',
  'Mime type' => '',
  'Name' => '',
  'Operations' => '',
  'Password' => '',
  'Please enter the letters as they are shown in the image above' => '',
  'Please fill out the following form with your login credentials' => '',
  'Privacy' => '',
  'Private' => '',
  'Public' => '',
  'Remember me next time' => '',
  'Save' => '',
  'Subject' => '',
  'Tags' => '',
  'Thank you' => '',
  'This page has been made by' => '',
  'This web application is a bookmark with more options' => '',
  'Update Bookmark' => '',
  'Update Document' => '',
  'Update Web' => '',
  'Username' => '',
  'Verification Code' => '',
  'View Bookmark' => '',
  'View Document' => '',
  'View Web' => '',
  'Webs' => '',
  'Welcome to' => '',
  'You may optionally enter a comparison operator' => '',
  'are required' => '',
  'at the beginning of each of your search values to specify how the comparison should be done' => '',
  'or' => '',
  'Create Resource' => '@@@@@@@@@@@@',
  'Document' => '@@@@@@@@',
  'View Resource' => '@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@',
  'Resources' => '@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@',
  'Submit1' => 'Submit',
);
